routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::group(['middleware' => 'auth'], function () {

    Route::resource('/', \App\Http\Controllers\DashboardController::class);
    Route::resource('inbound', \App\Http\Controllers\InboundController::class);
    Route::resource('/outbound', \App\Http\Controllers\OutboundController::class);
    Route::resource('/transactions', \App\Http\Controllers\TransactionHistoryController::class);
    Route::resource('/inventory', \App\Http\Controllers\InventoryController::class);
    Route::put('/inventory/{product_id}/qty/{qty_id}', [\App\Http\Controllers\InventoryController::class, 'updateQty'])
        ->name('inventory.updateQty');

    Route::resource('/merchants', \App\Http\Controllers\MerchantController::class);
    Route::resource('/staffs', \App\Http\Controllers\StaffController::class);
});

app/Http/Controllers/InventoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use Illuminate\Http\Request;

class InventoryController extends Controller
{
    /*
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'products' => Product::all()
        ];
        return view('pages.inventory.index')->with($data);
    }

    /*
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /*
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'productSKU' => 'required',
            'productName' => 'required'
        ]);

        $sku = $request->input('productSKU');
        $findIdentical = Product::where('product_sku', $sku)->first();
        if($findIdentical){
            return redirect()->back()->with('error', 'Product SKU already exists');
        }
        else {
            $product = new Product();
            $product->product_name = $request->input('productName');
            $product->product_sku = $sku;
            $product->save();
            return redirect()->back()->with('success', 'Product added successfully');
        }

    }

    /*
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
//
    }

    /*
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /*
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'productSKU' => 'required',
            'productName' => 'required',
            'productQuantity' => 'required'
        ]);

        $sku = $request->input('productSKU');
        $oldSKU = Product::find($id);
        $oldSKU = $oldSKU->product_sku;

        $findIdentical = Product::where('product_sku', $sku)->first();

        if($findIdentical && $oldSKU != $sku){
            return redirect()->back()->with('error', 'Product SKU already exists');
        } else {
            $product = Product::find($id);
            $product->product_name = $request->input('productName');
            $product->product_sku = $sku;
            $product->product_qty = $request->input('productQuantity');
            $product->save();
            return redirect()->back()->with('success', 'Product updated successfully');
        }
    }

    /*
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::find($id);
        $product->delete();
        return redirect()->back()->with('success', 'Product deleted successfully');
    }

    public function updateQty(Request $request, $id)
    {
        $this->validate($request, [
           'productQuantity' => 'required'
        ]);
        $qty = ExpiryDate::find($id);
        $qty->product_qty = $request->input('productQuantity');
        $qty->save();
        return redirect()->back()->with('success', 'Quantity updated successfully');
    }
}

resources/views/pages/inventory/index.blade.php
@extends('layouts.web')

@section('title', 'Stockmate | Inventory')

@section('content')

    <h1 class="h3 mb-4 text-gray-800">Inventory</h1>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <button class="btn btn-success" data-toggle="modal" data-target="#addProduct">Add Product</button>

        <div class="modal fade" id="addProduct" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add Product</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{{route('inventory.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="productName">Product Name</label>
                                <input type="text" class="form-control" name="productName" required>
                            </div>
                            <div class="form-group">
                                <label for="productName">Product SKU</label>
                                <input type="text" class="form-control" name="productSKU">
                            </div>
                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Add Product</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="inventory" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Product ID</th>
                        <th>Product SKU</th>
                        <th>Product Name</th>
                        <th>Total Qty</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                    <tr>
                        <td>{{$product->product_id}}</td>
                        <td>{{$product->product_sku}}</td>
                        <td>{{$product->product_name}}</td>
                        <td>{{$product->product_qty ? : 0}}</td>
                        <td>
                            <a href="#" data-toggle="modal" data-target="#editProduct{{$product->product_id}}" class="btn btn-primary btn-xs"><i class="fa fa-edit"></i></a>

                            <div class="modal fade" id="editProduct{{$product->product_id}}" tabindex="-1" role="dialog" aria-hidden="true">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <h5 class="modal-title" id="exampleModalLabel">Edit Product</h5>
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span>
                                            </button>
                                        </div>
                                        <form action="{{route('inventory.update', $product->product_id)}}" method="post">
                                            @csrf
                                            @method('put')
                                            <div class="modal-body">
                                                <div class="form-group">
                                                    <label for="productName">Product Name</label>
                                                    <input type="text" class="form-control" name="productName" value="{{$product->product_name}}" required>
                                                </div>
                                                <div class="form-group">
                                                    <label for="productName">Product SKU</label>
                                                    <input type="text" class="form-control" name="productSKU" value="{{$product->product_sku}}" required>
                                                </div>
                                                <div class="form-group">
                                                    <label for="productName">Product Quantity</label>
                                                    <input type="text" class="form-control" name="productQuantity" value="{{$product->product_qty ? : 0}}" required>
                                                </div>
                                            </div>
                                            <div class="modal-footer">
                                                <button type="submit" class="btn btn-primary">Update Product</button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>

{{--                            <form method="POST" style="display:inline;" action="{{route('inventory.destroy', $product->product_id)}}">--}}
{{--                                {{ method_field('DELETE') }}--}}
{{--                                {{ csrf_field() }}--}}
{{--                                <button onclick="return confirm('Are you sure to delete product \'{{$product->product_name}}\'?')" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>--}}
{{--                            </form>--}}
                        </td>
                    </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('additional-js')
    <script>
        $(document).ready(function() {
            $('#inventory').DataTable({
                ordering: true,
                searching: true,
                paging: true
            });
        });
    </script>
@endsection

resources/views/pages/inventory/show.blade.php
@extends('layouts.web')

@section('title', 'Product Detail')

@section('content')

    <h1 class="h3 mb-4 text-gray-800">Detail of - {{$product->product_sku}} / {{$product->product_name}}</h1>

    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="inventory" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Product Expiry Date</th>
                        <th>Product Qty</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                        @foreach($product->Expiry as $expiry)
                            <tr>
                                <td>{{$expiry->expiry_date}}</td>
                                <td>{{$expiry->product_qty}}</td>
                                <td>
                                    <a href="#" data-toggle="modal" data-target="#editProduct{{$expiry->expiry_date_id}}" class="btn btn-primary btn-xs"><i class="fa fa-edit"></i></a>

                                    <div class="modal fade" id="editProduct{{$expiry->expiry_date_id}}" tabindex="-1" role="dialog" aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header">
                                                    <h5 class="modal-title" id="exampleModalLabel">Adjust Quantity</h5>
                                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <form action="{{route('inventory.updateQty', [$product->product_id, $expiry->expiry_date_id] )}}" method="post">
                                                    @csrf
                                                    @method('put')
                                                    <div class="modal-body">
                                                        <div class="form-group">
                                                            <label for="productName">Product Qty</label>
                                                            <input type="text" class="form-control" name="productQuantity" value="{{$expiry->product_qty}}" required>
                                                        </div>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="submit" class="btn btn-primary">Update Quantity</button>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>



@endsection
@section('additional-js')
    <script>
        $(document).ready(function() {
            $('#inventory').DataTable({
                ordering: true,
                searching: true,
                paging: true
            });
        });
    </script>
@endsection