routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();



Route::group(['middleware' => 'auth'], function () {

    Route::resource('/', \App\Http\Controllers\DashboardController::class);
    Route::resource('inbound', \App\Http\Controllers\InboundController::class);
    Route::resource('/outbound', \App\Http\Controllers\OutboundController::class);
    Route::resource('/transactions', \App\Http\Controllers\TransactionHistoryController::class);
    Route::resource('/inventory', \App\Http\Controllers\InventoryController::class);
    Route::put('/inventory/{product_id}/qty/{qty_id}', [\App\Http\Controllers\InventoryController::class, 'updateQty'])
        ->name('inventory.updateQty');

    Route::resource('/merchants', \App\Http\Controllers\MerchantController::class);
    Route::resource('/staffs', \App\Http\Controllers\StaffController::class);
});

app/Models/Staff.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Staff extends Model
{
    protected $table = 'staffs';
    protected $primaryKey = 'staff_id';
    use HasFactory;
}

app/Http/Controllers/StaffController.php
<?php

namespace App\Http\Controllers;

use App\Models\Staff;
use Illuminate\Http\Request;

class StaffController extends Controller
{
    /*
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'staffs' => Staff::all()
        ];
        return view('pages.staffs.index')->with($data);
    }

    /*
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /*
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
           'staffName' => 'required',
           'staffGender' => 'required',
           'staffAddress' => 'required',
           'staffContact' => 'required',
        ]);

        $staff = new Staff();
        $staff->staff_name = $request->input('staffName');
        $staff->staff_gender = $request->input('staffGender');
        $staff->staff_address = $request->input('staffAddress');
        $staff->staff_contact = $request->input('staffContact');
        $staff->save();

        return redirect()->back()->with('success', 'Staff created successfully');
    }

    /*
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /*
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /*
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'staffName' => 'required',
            'staffGender' => 'required',
            'staffAddress' => 'required',
            'staffContact' => 'required',
        ]);

        $staff = Staff::find($id);
        $staff->staff_name = $request->input('staffName');
        $staff->staff_gender = $request->input('staffGender');
        $staff->staff_address = $request->input('staffAddress');
        $staff->staff_contact = $request->input('staffContact');
        $staff->save();

        return redirect()->back()->with('success', 'Staff updated successfully');
    }

    /*
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/staffs/index.blade.php
@extends('layouts.web')

@section('title', 'Stockmate | Staffs')

@section('content')

    <h1 class="h3 mb-4 text-gray-800">Staff List</h1>

    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <button class="btn btn-success" data-toggle="modal" data-target="#addStaff">Add Staff</button>

        <div class="modal fade" id="addStaff" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Add Staff</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <form action="{{route('staffs.store')}}" method="post" enctype="multipart/form-data">
                        @csrf
                        <div class="modal-body">
                            <div class="form-group">
                                <label for="staffName">Staff Name</label>
                                <input type="text" class="form-control" name="staffName" required>
                            </div>
                            <div class="form-group">
                                <label for="staffName">Staff Address</label>
                                <input type="text" class="form-control" name="staffAddress">
                            </div>
                            <div class="form-group">
                                <label for="staffName">Staff Contact</label>
                                <input type="text" class="form-control" name="staffContact">
                            </div>
                            <div class="form-group">
                                <label for="staffName">Staff Gender</label>
                                <select class="form-control" name="staffGender" required>
                                    <option value="" selected disabled>--choose gender--</option>
                                    <option value="1">Male</option>
                                    <option value="0">Female</option>
                                </select>
                            </div>

                        </div>
                        <div class="modal-footer">
                            <button type="submit" class="btn btn-success">Add Staff</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered" id="staffs" width="100%" cellspacing="0">
                    <thead>
                    <tr>
                        <th>Staff ID</th>
                        <th>Staff Name</th>
                        <th>Staff Address</th>
                        <th>Staff Contact</th>
                        <th>Staff Gender</th>
                        <th>Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($staffs as $staff)
                        <tr>
                            <td>{{$staff->staff_id}}</td>
                            <td>{{$staff->staff_name}}</td>
                            <td>{{$staff->staff_address}}</td>
                            <td>{{$staff->staff_contact}}</td>
                            <td>{{$staff->staff_gender == 1 ? 'Male' : 'Female'}}</td>
                            <td>
                                <a href="#" data-toggle="modal" data-target="#editStaff{{$staff->staff_id}}" class="btn btn-primary btn-xs"><i class="fa fa-edit"></i></a>

                                <div class="modal fade" id="editStaff{{$staff->staff_id}}" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h5 class="modal-title" id="exampleModalLabel">Edit Staff</h5>
                                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                    <span aria-hidden="true">&times;</span>
                                                </button>
                                            </div>
                                            <form action="{{route('staffs.update', $staff->staff_id)}}" method="post">
                                                @csrf
                                                @method('put')
                                                <div class="modal-body">
                                                    <div class="form-group">
                                                        <label for="staffName">Staff Name</label>
                                                        <input type="text" class="form-control" name="staffName" value="{{$staff->staff_name}}" required>
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="staffName">Staff Address</label>
                                                        <input type="text" class="form-control" name="staffAddress" value="{{$staff->staff_address}}">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="staffName">Staff Contact</label>
                                                        <input type="text" class="form-control" name="staffContact" value="{{$staff->staff_contact}}">
                                                    </div>
                                                    <div class="form-group">
                                                        <label for="staffName">Staff Gender</label>
                                                        <select class="form-control" name="staffGender">
                                                            <option value="1" {{$staff->staff_gender == 1 ? 'selected' : ''}}>Male</option>
                                                            <option value="0" {{$staff->staff_gender == 0 ? 'selected' : ''}}>Female</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="modal-footer">
                                                    <button type="submit" class="btn btn-primary">Update Staff</button>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>

{{--                                <form method="POST" style="display:inline;" action="{{route('staffs.destroy', $staff->staff_id)}}">--}}
{{--                                    {{ method_field('DELETE') }}--}}
{{--                                    {{ csrf_field() }}--}}
{{--                                    <button onclick="return confirm('Are you sure to delete staff \'{{$staff->staff_name}}\'?')" class="btn btn-danger btn-xs"><i class="fa fa-trash"></i></button>--}}
{{--                                </form>--}}
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection

@section('additional-js')
    <script>
        $(document).ready(function() {
            $('#staffs').DataTable({
                ordering: true,
                searching: true,
                paging: true
            });
        });
    </script>
@endsection